"""payments module tables

Revision ID: c3f7b02cfd91
Revises: e6204c4bba43
Create Date: 2022-09-25 01:54:39.072330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f7b02cfd91'
down_revision = 'e6204c4bba43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
