"""operation module table

Revision ID: e6204c4bba43
Revises: ecb14a3ca1c3
Create Date: 2022-09-25 00:51:28.440644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6204c4bba43'
down_revision = 'ecb14a3ca1c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
